name: poker_simulations
description: A library for modeling and simulating poker hands.
version: 0.1.2
repository: https://github.com/ram6ler/poker_simulations

environment:
  sdk: ^3.8.1

dependencies:
  trotter: ^2.2.2

dev_dependencies:
  lints: ^6.0.0


